name: Build Nest Stream Flink JAR and Submit Jobs
on:
  push:
    branches: [ main ]  
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: choice
        options:
          - beta
          - prod
        required: true
      version:
        description: 'version'
        type: text
        required: true

jobs:
  release:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Version: $VERSION"
          echo "Environment: $ENVIRONMENT"
        env:
          VERSION: ${{ inputs.version }}
          ENVIRONMENT: ${{ inputs.environment }}
          
  Build:
    name: Build Nest Stream Flink JAR
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: echo 'Build'

      - name: Submit Jar
        run: echo 'Submit Jar'
        
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "latest"
          force_push_tag: true
          message: "Latest release"

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "v1.0.0"
          force_push_tag: true
          message: "v1.0.0 release"


  Deploy:
    name: Deploy_product_product
    if: github.event.ref == 'refs/heads/main'
    # Set the type of machine to run on
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          java-package: jdk
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - uses: kanga333/variable-mapper@master
        with:
          key: "${{github.ref}}"
          map: |
            {
              "refs/heads/team": {
                "environment": "red,green"
              },
              "refs/heads/develop": {
                "environment": "dev"
              },
              "refs/heads/main": {
                "environment": "stg"
              }
            }
      - name: Set Release version env variable
        run: |
          echo "JAR_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: POM version
        run: echo 'Pom version = ${{env.JAR_VERSION}}'
      - name: Execute deploy python script
        run: python config.py -e ${{env.environment}} -jv ${{env.JAR_VERSION}}
