name: Build Nest Stream Flink JAR and Submit Jobs
on:
  push:
    branches: [ main ]

jobs:        
  Build:
    name: Build Nest Stream Flink JAR
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
      - name: Build
        run: echo 'Build'

      - name: Submit Jar
        run: echo 'Submit Jar'

  Deploy:
    name: Deploy_product_product
    if: github.event.ref == 'refs/heads/main'
    # Set the type of machine to run on
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v1
      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: './config.yml'          # File to read from
          key-path: '["v1", "green"]' # Access the runs key then the using key and retuns the value.

      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"

      - name: Submit product_product job
        run: echo 'Submit product_product job'
